# Docker Compose configuration for Keycloak and PostgreSQL database
services:
  # PostgreSQL database service for Keycloak
  keycloak-db:
    image: postgres:16-alpine
    container_name: trencadis-auth-db
    networks:
      - trencadis-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: trencadis-keycloak
    command: start-dev --import-realm
    networks:
      - trencadis-network
    environment:
      KC_DB: postgres
      KC_DB_URL: ${DB_URL}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
    depends_on:
      - keycloak-db

networks:
  trencadis-network:
    driver: bridge

volumes:
  postgres_data: